const Articles = [
  {
    userID: 1,
    username: "yolo",
    text: "This article is short.",
  },
  {
    userID: 2,
    username: "zum_zum",
    text: "Man, this article is so long ow mah gawd!!",
  },
  { userID: 1, username: "yolo", text: "This article is boring." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
  { userID: 2, username: "zum_zum", text: "This article is a copy." },
];

export default Articles;
